### ISSUE TITLE
请问java和maven版本用的是什么？

### ISSUE THREAD

**Issue by OnlyWolfy** [AioliaCodeGeass/community#1]
试了java17、12和8都运行报错，maven用的是3.8.6

**Comment by AioliaCodeGeass** [comment]
java用的java8,maven 3.8.6，看看是不是别的服务没配置好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AioliaCodeGeass/community"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月7日(星期五) 中午1:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[AioliaCodeGeass/community] 请问java和maven版本用的是什么？ (Issue #1)





 
试了java17、12和8都运行报错，maven用的是3.8.6

**Comment by OnlyWolfy** [comment]
好的谢谢Thanks♪(･ω･)ﾉ
